"""Connector admission contracts for deterministic offline admission."""

from millforge.connectors.contracts import (
    CONNECTOR_ADMISSION_MANIFEST_KIND,
    CONNECTOR_ADMISSION_MANIFEST_SCHEMA,
    CONNECTOR_ADMISSION_MANIFEST_VERSION,
    CONNECTOR_ADMISSION_RECORD_HASH_KIND,
    CONNECTOR_DISCOVERY_SNAPSHOT_HASH_KIND,
    CONNECTOR_DISCOVERY_TOOL_HASH_KIND,
    CONNECTOR_IDENTITY_HASH_KIND,
    ConnectorAdmissionManifest,
    ConnectorAdmissionPolicy,
    ConnectorAdmissionRecord,
    ConnectorAdmissionResult,
    ConnectorApprovalPolicy,
    ConnectorContractValidation,
    ConnectorDiscoverySnapshot,
    ConnectorIdentity,
    ConnectorProtocol,
    ConnectorToolSelection,
    ConnectorTransportKind,
    DeniedConnectorTool,
    DescriptionPolicy,
    DiscoveredProviderTool,
    ExpectedConnectorIdentity,
    InputSchemaPolicy,
    OutputSchemaPolicy,
)
from millforge.connectors.diagnostics import (
    ConnectorDiagnostic,
    ConnectorDiagnosticCode,
    ConnectorDiagnosticEvidence,
    ConnectorDiagnosticPhase,
    ConnectorDiagnosticSeverity,
    connector_diagnostic,
    malformed_input_diagnostic,
)
from millforge.connectors.admission import admit_connector_tools
from millforge.connectors.broker import (
    ConnectorBroker,
    ConnectorBrokerOutcome,
    ConnectorInvocationRequest,
    ConnectorProviderToolEvidence,
    connector_idempotency_key,
)
from millforge.connectors.fake import DeterministicFakeConnectorBroker
from millforge.connectors.runtime import (
    ConnectorAdmissionBinding,
    ConnectorAdmissionSnapshot,
    ConnectorAdmissionSnapshotError,
)

__all__ = [
    "CONNECTOR_ADMISSION_MANIFEST_KIND",
    "CONNECTOR_ADMISSION_MANIFEST_SCHEMA",
    "CONNECTOR_ADMISSION_MANIFEST_VERSION",
    "CONNECTOR_ADMISSION_RECORD_HASH_KIND",
    "CONNECTOR_DISCOVERY_SNAPSHOT_HASH_KIND",
    "CONNECTOR_DISCOVERY_TOOL_HASH_KIND",
    "CONNECTOR_IDENTITY_HASH_KIND",
    "ConnectorAdmissionManifest",
    "ConnectorAdmissionPolicy",
    "ConnectorAdmissionRecord",
    "ConnectorAdmissionResult",
    "ConnectorAdmissionBinding",
    "ConnectorAdmissionSnapshot",
    "ConnectorAdmissionSnapshotError",
    "ConnectorBroker",
    "ConnectorBrokerOutcome",
    "ConnectorInvocationRequest",
    "ConnectorProviderToolEvidence",
    "ConnectorApprovalPolicy",
    "ConnectorContractValidation",
    "ConnectorDiagnostic",
    "ConnectorDiagnosticCode",
    "ConnectorDiagnosticEvidence",
    "ConnectorDiagnosticPhase",
    "ConnectorDiagnosticSeverity",
    "ConnectorDiscoverySnapshot",
    "ConnectorIdentity",
    "ConnectorProtocol",
    "ConnectorToolSelection",
    "ConnectorTransportKind",
    "DeniedConnectorTool",
    "DeterministicFakeConnectorBroker",
    "DescriptionPolicy",
    "DiscoveredProviderTool",
    "ExpectedConnectorIdentity",
    "InputSchemaPolicy",
    "OutputSchemaPolicy",
    "admit_connector_tools",
    "connector_idempotency_key",
    "connector_diagnostic",
    "malformed_input_diagnostic",
]
