"""Custom-tool contracts for deterministic offline compilation."""

from millforge.custom_tools.contracts import (
    CUSTOM_TOOL_COMPILATION_RECORD_HASH_KIND,
    CUSTOM_TOOL_DECLARATION_HASH_KIND,
    CUSTOM_TOOL_SOURCE_HASH_KIND,
    CUSTOM_TOOL_SOURCE_KIND,
    CUSTOM_TOOL_SOURCE_SCHEMA,
    CUSTOM_TOOL_SOURCE_VERSION,
    CustomToolApprovalPolicy,
    CustomToolCompilationRecord,
    CustomToolCompilationResult,
    CustomToolCompilerPolicy,
    CustomToolContractModel,
    CustomToolContractValidation,
    CustomToolDeclaration,
    CustomToolDescriptionPolicy,
    CustomToolInputPolicy,
    CustomToolOutputPolicy,
    CustomToolRuntimeKind,
    CustomToolSourceManifest,
    compilation_record_from_declaration,
    tool_descriptor_from_declaration,
)
from millforge.custom_tools.compiler import compile_custom_tools
from millforge.custom_tools.diagnostics import (
    CustomToolDiagnostic,
    CustomToolDiagnosticCode,
    CustomToolDiagnosticEvidence,
    CustomToolDiagnosticPhase,
    CustomToolDiagnosticSeverity,
    custom_tool_diagnostic,
    malformed_input_diagnostic,
    redact_custom_tool_text,
)

__all__ = [
    "CUSTOM_TOOL_COMPILATION_RECORD_HASH_KIND",
    "CUSTOM_TOOL_DECLARATION_HASH_KIND",
    "CUSTOM_TOOL_SOURCE_HASH_KIND",
    "CUSTOM_TOOL_SOURCE_KIND",
    "CUSTOM_TOOL_SOURCE_SCHEMA",
    "CUSTOM_TOOL_SOURCE_VERSION",
    "CustomToolApprovalPolicy",
    "CustomToolCompilationRecord",
    "CustomToolCompilationResult",
    "CustomToolCompilerPolicy",
    "CustomToolContractModel",
    "CustomToolContractValidation",
    "CustomToolDeclaration",
    "CustomToolDescriptionPolicy",
    "CustomToolDiagnostic",
    "CustomToolDiagnosticCode",
    "CustomToolDiagnosticEvidence",
    "CustomToolDiagnosticPhase",
    "CustomToolDiagnosticSeverity",
    "CustomToolInputPolicy",
    "CustomToolOutputPolicy",
    "CustomToolRuntimeKind",
    "CustomToolSourceManifest",
    "compilation_record_from_declaration",
    "compile_custom_tools",
    "custom_tool_diagnostic",
    "malformed_input_diagnostic",
    "redact_custom_tool_text",
    "tool_descriptor_from_declaration",
]
